language: node_js
dist: trusty
addons:
  sonarcloud:
    organization: "yoshienverde-github"
#    token:
#      secure: ********* # encrypted value of your token
branches:
  only:
  - master
  - stable
  - v0
cache:
  directories:
  - node_modules
before_install:
- npm update
install:
- npm install
script:
- npm test
- npm run coveralls
- sonar-scanner